permissions:
  contents: write
  
  name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://sungeui.github.io/

      - name: Commit sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push 
